random_state: 42
col_id: id_employee
target: a_quitte_l_entreprise
subsample_frac: 0.5

paths:
  sirh: ../data/raw/sirh.csv
  evaluation: ../data/raw/evaluation.csv
  sondage: ../data/raw/sondage.csv
  sql_file: ../reports/merge_sql.sql
  db_file: ../data/interim/merge_temp.db

num_cols:
  - age
  - revenu_mensuel
  - annees_dans_l_entreprise
  - annees_dans_le_poste_actuel
  - annees_depuis_la_derniere_promotion
  - distance_domicile_travail
  - nombre_participation_pee
  - note_evaluation_actuelle
  - note_evaluation_precedente
  - annees_depuis_le_changement_deposte
  - annee_experience_totale
  - nb_formations_suivies
  - satisfaction_employee_environnement
  - satisfaction_employee_nature_travail
  - satisfaction_employee_equipe
  - satisfaction_employee_equilibre_pro_perso
  - augmentation_par_revenu
  - annee_sur_poste_par_experience
  - nb_formation_par_experience
  - score_moyen_satisfaction
  - dern_promo_par_experience
  - evolution_note

cat_cols:
  - genre
  - departement
  - frequence_deplacement
  - etat_civil
  - niveau_etudes
  - role
  - type_contrat

sat_cols:
  - satisfaction_employee_environnement
  - satisfaction_employee_nature_travail
  - satisfaction_employee_equipe
  - satisfaction_employee_equilibre_pro_perso

first_vars:
  - age
  - revenu_mensuel
  - annees_dans_l_entreprise
  - note_evaluation_actuelle
